services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_HOST}
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready - U ${DB_USER} -d ${DB_HOST}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_ACTOR=${GITHUB_ACTOR}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

      GEMINI_API_KEY: ${GEMINI_KEY}

      acess_jwt_secret: ${acess_jwt_secret}
      refresh_jwt_secret: ${refresh_jwt_secret}
      pre_auth_token: ${pre_auth_token}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}

      MINIO_URL: http://financas-minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    depends_on:
      db:
        condition: service_started

  minio:
    image: minio/minio
    container_name: financas-minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

volumes:
  pg_data: