spring.config.import=optional:file:.env[.properties]

spring.application.name=financas

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.vertex.ai.gemini.location=us-central1
